### ISSUE TITLE
Can't specify Alt. Paths for environment variables other than installlocation

### ISSUE THREAD

**Issue by sanmadjack** [MASGAU/MASGAU#17]
Add the ability to add alt. paths for environment variables besides installlocation, OR change alt. paths so that they are acceptable substitutes for ALL environment variables.

**Comment by AvvAdeh** [comment]
I like alternative options, but I would need an example to understand how this could be useful, yet I can't see what would be the advantage of it. Theoretically environment variables are useful at giving a path whatever this path is, ie: if I move 'My Documents' folder (or any special folder covered by environment variables) to another drive than the system one, the environment variable would give the correct path, so what would be the point of searching for it in an alt.path?

**Comment by sanmadjack** [comment]
The root of this is some reports I've received that have steamapps moved to a different folder. At present, there is no internal way for MASGAU to accomodate this, so I'm brainstorming ways to allow the user to change these paths.

**Comment by AvvAdeh** [comment]
Okay, I searched a bit to see how one can move its steamapps folder to another place, without success.
My first move would be to contact the guys with moved steamapps to know how they did this, because if they did, there must be a way to find out this folder (because Steam find it).
I think I understand what you want to achieve with alt path, it would allow to avoid any weird user change from stopping MASGAU to work. I guess it would be good enough, but if this issue only touches Steam and eventually GoG, I think it would be better to rule only these paths, instead of everyone, and if it only touches Steam, then it is better to add a field to point to an alt. path only about steamapps path.
Still, I find it weird that people move only their steamapps folder instead of the whole Steam folder, I can't see the point...

**Comment by sanmadjack** [comment]
It's the result of making a steam game run without steam.

**Comment by AvvAdeh** [comment]
But then, what is the path used instead of steamapps folder? Isn't it a well known folder? 
Isn't it related to game natural behaviour with its savegame files (like if the game was non-steam retail)?

**Comment by sanmadjack** [comment]
Nope! It's a result of using cracks to force a steam-only game to run without steam. It saves exactly like it was using the steam cloud, but to some arbitrary folder determined by the cracker/user. While I don't condone piracy, I recognize the legitimate use of cracks.

**Comment by AvvAdeh** [comment]
Aow :)
 I too think that as long as crap limit exists, cracks have their legitimate place. I could speak hours on this subject...

In this case, you have to see if allowing alt. paths to become environment variable won't do problem, if not do so, if yes perhaps do a special field for environment replacement paths.

**Comment by sanmadjack** [comment]
Rather than make a change to how MASGAU works with things, now for games that can keep their saves elsewhere, I'm adding an alt save path entry to the xml profile.
