### ISSUE TITLE
UI change request: No games detected/Archives found during scan.

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#22]
It's a bit confusing, possibly disconcerting to see "No games detected" and especially "No Archives found" when first viewing those respective tabs. 

Immediate fix: Set initial text to something more accurate/benign like "initializing".

Possible enhancement: Save a list of known games/saves on that system (simple text file), read that upon startup, and list those items in greyed-out format whilst scanning. Maybe not auto-scan for games on each launch? (There's already a re-scan games button.) Save-games it probably makes sense to leave as-is.

**Comment by sanmadjack** [comment]
You make a good point about the initial message, that should be more accurate than it is.

As for the possible enhancement, the first build before I released MASGAU had detection caching, but as I went on I came to the conclusion that MASGAU needed to provide as accurate information as possible whenever it was launched. That requires auto-redetection every time it launches, and I decided that rather than relying on the crutch of caching, I would put more effort into improving detection speed. I'm sure there are more improvements that can be made in that area, but I find the detection speed to be more than adequate for now (over 1,000 entries scanned for in about 10 seconds on my crappy mid-2000s laptop)
