### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by ghost** [MASGAU/MASGAU#34]
I would like to see a Standard/Portable installation for MasGau as I like to take my stuff on the go. Using a Portable.ini file and just check for it's existence. If yes, portable mode, checking beneath the existing EXE folder and avoid using the registry. If not, check the users folder instead. Simply use InnoSetup to create the files and folders accordingly. Rainmeter does exactly this and it seems to be a hit with both crowds.

**Comment by sanmadjack** [comment]
I've started implementing it. The installer will include a checkable option to change it to a portable installation. This will be achieved by placing a settings.xml file in the install folder. In this mode, the game xmls in the data folder will be directly used. I'll be important to install this to a location that is writable to any users, otherwise the settings.xml and update system will freak out royally.

**Comment by sanmadjack** [comment]
Confirmed today that this is working properly. Awesome!
