### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#54]
I currently have 3 suggestions I wanted to air out (could be more in the future).

1)  Regarding folder browser dialog, why not use the "vista" style one, I recently found a project upgraded to .NET 4 client which uses the vistabridge to show a folder dialog. (http://wpffolderbrowser.codeplex.com/)
2) On specific Messages (like the multiple games message) add a message that shows to not remind me (or something similiar)
3) Ability to delete specific archives, or overwrite with a totally new one (annoyed me sometimes that it saved old saves, after they where deleted with purpose)

**Comment by sanmadjack** [comment]
Well, I'll address all these here, but each of these should really have been made its own issue.

1) That would be nice, but it's hardly a priority. I'm reviewing the code for the vista bridge stuff, I'll try to work it in at some point. 

2) A lot of dialogs already have this, and I'm going to be adding 

3) One of the key rules of a backup program is that it should never automatically delete data. So MASGAU will never delete a save just because it was deleted from the save folder. If it did, then it would do it even if you accidentally deleted it. Technically you're able to delete archives from the file browser, but what you're asking is a button to delete selected archives? 

Could you please create an individual issue for 1 and 3? 2 is already in progress, and any other dialogs you think should get a "stop notifying me" check box should get their own issue as well.
