### ISSUE TITLE
Duplicate game priority

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#59]
When there is a duplicate game in c.xml (could be others as well) and custom.xml,
MASGAU is prioritizing the duplicate in c.xml instead of the newer one in custom.xml.

However when it p.xml it does prioritize the one in custom.xml, from what I gather from this
MASGAU is selecting the first occurrence of the game it finds.

**Comment by sanmadjack** [comment]
Your understanding of internal priority is correct, but this issue is a moot point. None of those files should be manually modified, the letter ones are only changed through auto-update, and the custom.xml is only for MASGAU's custom game feature. The new.xml file should always contain user-created data, and it will always take priority over any other file. It won't even nag you about duplicates if you put them in there. I'm going to update the description string to explain this.

**Comment by AdmiringWorm** [comment]
ah, then it's just me who have been using it wrong. Always used the custom.xml not new.xml
