### ISSUE TITLE
Ability to delete gamesaves.

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#70]
New Feature/UI request:

MASGAU is great for showing what crud is left over from demos, old games, etc. It's nice that I can hover over "BoogerBlaster 3: Electric Boogerloo" and be shown the path, I would like to be able to right-click\*  and select either "Delete Save", "Delete All active files" or "Open Explorer" which would of course open to the relevant path.

*I'd like a right-click menu for the main features as well, but that's another request I suppose.

**Comment by sanmadjack** [comment]
One of the concepts I've been actively pursuing is to not have a right-click menu in MASGAU anymore. It's not an ideological mandate, but it does guide me to "trim the fat" so to speak in order to make everything fit. If there was a compelling enough reason I'd add one in, but I'm not sure this request qualifies. There are already buttons to delete a game's archives and purge the detected files, but nothing for opening the game's path. 

I can kind of see it being nice to have, but I'm not sure I see a real demand for it. How were you imagining it being useful?

**Comment by OranguTech** [comment]
Begin thread necromancy:

Right-click was just the "natural" way I expected it to work, esp. since you're getting info via a hover, but it was "purge" functionality I was concerned about, which I didn't realize was an implemented feature at the time. (Or wasn't updated then or...) Anyway, thanks for "Purge" button. :+1:
